### ISSUE TITLE
Is this the new home for find-and-replace-maven-plugin

### ISSUE THREAD

**Issue by hazendaz** [xdev-software/find-and-replace-maven-plugin#45]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/find-and-replace-maven-plugin/issues) or [closed](https://github.com/xdev-software/find-and-replace-maven-plugin/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

As we know the original plugin is not getting releases.  It may get one today though.  But longer term seems original author isn't using it as was the case before.  There are some threads over there discussing it today.  This fork is certainly in a better spot currently but want to understand if the support will be on this fork if the original is set to archived.  My personal main concerns are the same I think with it working on newer maven properly without warnings.  And the original broke today with maven 3.9.8 (needed commons lang3) that is removed here.

### Additional information

See comments from here https://github.com/floverfelt/find-and-replace-maven-plugin/pull/11.

I'm also willing to help out as I have extensive maven knowledge and maintain a number of maven plugins and even wrote some myself.  I'm also the current maintainer of spotbugs-maven-plugin which is probably the largest used one I directly work on.  To a limited extent I have done commits into various maven owned plugins over the years as well.

**Comment by AB-xdev** [comment]
0 communication from the original plugin author since this first popped up so I guess I can close this for now...

**Comment by hazendaz** [comment]
Sorry never responded back.  The original plugin did move again but trying to use it today on a project where I need to touch the manifest file and colon trips it up.  Switched to yours and it works perfectly!  So going to switch over here as original project indicated not much going to go on there post the maven 3.9 / maven 4.0 support work.

**Comment by hazendaz** [comment]
> Sorry never responded back. The original plugin did move again but trying to use it today on a project where I need to touch the manifest file and colon trips it up. Switched to yours and it works perfectly! So going to switch over here as original project indicated not much going to go on there post the maven 3.9 / maven 4.0 support work.

issue actually was on windows using ${project.basedir} in the basedir entry.  This plugin likes it, the original does not.  So not a content issue but just interesting.
